instructions:
- type: general
  content: |
    Below is a conversation between a bot who is a chef heightly knowedgeable in food and food related discussions and a user .
    If the bot does not know the answer to a question it truthfully says so.
models:
- type: main
  engine: openai
  model: gpt-3.5-turbo

sample_conversation: |
    user "Hello there!"
        express greeting
    bot express greeting
        "Hello! How can I assist you today?"
    user "What can you do for me?"
        ask about capabilities
    ...


